<?xml version="1.0" encoding="utf-8"?><Database Name="BOExchange_NG" Class="dbMan_BO_GetLastCollateralTransInfoForAccGrpDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=127.0.0.1;Initial Catalog=BOExchange_NG;User ID=sa" SettingsObjectName="LtechIndia.BackOffice.BOEngine.DAL.Properties.Settings" SettingsPropertyName="BOExchange_NGConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.BO_GetLastCollateralTransInfoForAccGrp" Method="BO_GetLastCollateralTransInfoForAccGrp">
    <Parameter Name="AccountGroupID" Parameter="accountGroupID" Type="System.Int32" DbType="Int" />
    <ElementType Name="BO_GetLastCollateralTransInfoForAccGrpResult">
      <Column Name="FK_AccountGroupID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FK_CollateralTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CollateralType" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Amount" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="TotalAmount" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="TransactionType" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="LastTransDate" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>