#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LtechIndia.BackOffice.BOEngine.DAL.DB_New
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BOExchange_NG")]
	public partial class dbMan_BO_GetClientAccountInformationDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public dbMan_BO_GetClientAccountInformationDataContext() : 
				base(global::LtechIndia.BackOffice.BOEngine.DAL.Properties.Settings.Default.BOExchange_NGConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dbMan_BO_GetClientAccountInformationDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbMan_BO_GetClientAccountInformationDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbMan_BO_GetClientAccountInformationDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbMan_BO_GetClientAccountInformationDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.BO_GetClientAccountInformation")]
		public ISingleResult<BO_GetClientAccountInformationResult> BO_GetClientAccountInformation([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ClientID", DbType="Int")] System.Nullable<int> clientID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), clientID);
			return ((ISingleResult<BO_GetClientAccountInformationResult>)(result.ReturnValue));
		}
	}
	
	public partial class BO_GetClientAccountInformationResult
	{
		
		private int _PK_AccountId;
		
		private int _FK_ParticipantID;
		
		private int _FK_AccountGroupID;
		
		private decimal _Balance;
		
		private decimal _Equity;
		
		private System.Nullable<bool> _Deleted;
		
		private decimal _UsedMargin;
		
		private int _FK_Leverage;
		
		private System.Nullable<bool> _IsHedgingAllowed;
		
		private System.Nullable<bool> _IsTradeEnable;
		
		private int _FK_Currency;
		
		private decimal _BuySideTurnOver;
		
		private decimal _SellSideTurnOver;
		
		private int _FK_BankID;
		
		private decimal _ReserveMargin;
		
		private decimal _DayBuySideTurnOver;
		
		private decimal _DaySellSideTurnOver;
		
		private decimal _DayRealizedProfit;
		
		private string _LP_Name;
		
		private string _LPConnectionAccountID;
		
		private System.Nullable<bool> _IsLive;
		
		private System.Nullable<int> _FK_HedgeType_ID;
		
		public BO_GetClientAccountInformationResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PK_AccountId", DbType="Int NOT NULL")]
		public int PK_AccountId
		{
			get
			{
				return this._PK_AccountId;
			}
			set
			{
				if ((this._PK_AccountId != value))
				{
					this._PK_AccountId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_ParticipantID", DbType="Int NOT NULL")]
		public int FK_ParticipantID
		{
			get
			{
				return this._FK_ParticipantID;
			}
			set
			{
				if ((this._FK_ParticipantID != value))
				{
					this._FK_ParticipantID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_AccountGroupID", DbType="Int NOT NULL")]
		public int FK_AccountGroupID
		{
			get
			{
				return this._FK_AccountGroupID;
			}
			set
			{
				if ((this._FK_AccountGroupID != value))
				{
					this._FK_AccountGroupID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Balance", DbType="Decimal(18,5) NOT NULL")]
		public decimal Balance
		{
			get
			{
				return this._Balance;
			}
			set
			{
				if ((this._Balance != value))
				{
					this._Balance = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Equity", DbType="Decimal(18,5) NOT NULL")]
		public decimal Equity
		{
			get
			{
				return this._Equity;
			}
			set
			{
				if ((this._Equity != value))
				{
					this._Equity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Deleted", DbType="Bit")]
		public System.Nullable<bool> Deleted
		{
			get
			{
				return this._Deleted;
			}
			set
			{
				if ((this._Deleted != value))
				{
					this._Deleted = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsedMargin", DbType="Decimal(18,5) NOT NULL")]
		public decimal UsedMargin
		{
			get
			{
				return this._UsedMargin;
			}
			set
			{
				if ((this._UsedMargin != value))
				{
					this._UsedMargin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_Leverage", DbType="Int NOT NULL")]
		public int FK_Leverage
		{
			get
			{
				return this._FK_Leverage;
			}
			set
			{
				if ((this._FK_Leverage != value))
				{
					this._FK_Leverage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsHedgingAllowed", DbType="Bit")]
		public System.Nullable<bool> IsHedgingAllowed
		{
			get
			{
				return this._IsHedgingAllowed;
			}
			set
			{
				if ((this._IsHedgingAllowed != value))
				{
					this._IsHedgingAllowed = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsTradeEnable", DbType="Bit")]
		public System.Nullable<bool> IsTradeEnable
		{
			get
			{
				return this._IsTradeEnable;
			}
			set
			{
				if ((this._IsTradeEnable != value))
				{
					this._IsTradeEnable = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_Currency", DbType="Int NOT NULL")]
		public int FK_Currency
		{
			get
			{
				return this._FK_Currency;
			}
			set
			{
				if ((this._FK_Currency != value))
				{
					this._FK_Currency = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BuySideTurnOver", DbType="Decimal(18,2) NOT NULL")]
		public decimal BuySideTurnOver
		{
			get
			{
				return this._BuySideTurnOver;
			}
			set
			{
				if ((this._BuySideTurnOver != value))
				{
					this._BuySideTurnOver = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SellSideTurnOver", DbType="Decimal(18,2) NOT NULL")]
		public decimal SellSideTurnOver
		{
			get
			{
				return this._SellSideTurnOver;
			}
			set
			{
				if ((this._SellSideTurnOver != value))
				{
					this._SellSideTurnOver = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_BankID", DbType="Int NOT NULL")]
		public int FK_BankID
		{
			get
			{
				return this._FK_BankID;
			}
			set
			{
				if ((this._FK_BankID != value))
				{
					this._FK_BankID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReserveMargin", DbType="Decimal(18,2) NOT NULL")]
		public decimal ReserveMargin
		{
			get
			{
				return this._ReserveMargin;
			}
			set
			{
				if ((this._ReserveMargin != value))
				{
					this._ReserveMargin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DayBuySideTurnOver", DbType="Decimal(18,2) NOT NULL")]
		public decimal DayBuySideTurnOver
		{
			get
			{
				return this._DayBuySideTurnOver;
			}
			set
			{
				if ((this._DayBuySideTurnOver != value))
				{
					this._DayBuySideTurnOver = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DaySellSideTurnOver", DbType="Decimal(18,2) NOT NULL")]
		public decimal DaySellSideTurnOver
		{
			get
			{
				return this._DaySellSideTurnOver;
			}
			set
			{
				if ((this._DaySellSideTurnOver != value))
				{
					this._DaySellSideTurnOver = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DayRealizedProfit", DbType="Decimal(18,2) NOT NULL")]
		public decimal DayRealizedProfit
		{
			get
			{
				return this._DayRealizedProfit;
			}
			set
			{
				if ((this._DayRealizedProfit != value))
				{
					this._DayRealizedProfit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LP_Name", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string LP_Name
		{
			get
			{
				return this._LP_Name;
			}
			set
			{
				if ((this._LP_Name != value))
				{
					this._LP_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LPConnectionAccountID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string LPConnectionAccountID
		{
			get
			{
				return this._LPConnectionAccountID;
			}
			set
			{
				if ((this._LPConnectionAccountID != value))
				{
					this._LPConnectionAccountID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsLive", DbType="Bit")]
		public System.Nullable<bool> IsLive
		{
			get
			{
				return this._IsLive;
			}
			set
			{
				if ((this._IsLive != value))
				{
					this._IsLive = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_HedgeType_ID", DbType="Int")]
		public System.Nullable<int> FK_HedgeType_ID
		{
			get
			{
				return this._FK_HedgeType_ID;
			}
			set
			{
				if ((this._FK_HedgeType_ID != value))
				{
					this._FK_HedgeType_ID = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
