<?xml version="1.0" encoding="utf-8"?>
<Database Name="BOExchange" Class="dbMan_BO_GetClientAccountTypesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=192.168.1.5;Initial Catalog=BOExchange;User ID=sa" SettingsObjectName="LtechIndia.BackOffice.BOEngine.DAL.Properties.Settings" SettingsPropertyName="BOExchangeConnectionString5" Provider="System.Data.SqlClient" />
  <Function Name="dbo.BO_GetAccountTypes" Method="BO_GetAccountTypes">
    <ElementType Name="BO_GetAccountTypesResult">
      <Column Name="PK_AccountTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AccountTypeName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>