<?xml version="1.0" encoding="utf-8"?>
<Database Name="BOExchange_NG" Class="dbMan_BO_DeleteSymbolSessionNewDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=BOExchange_NG;Integrated Security=True" SettingsObjectName="LtechIndia.BackOffice.BOEngine.DAL.Properties.Settings" SettingsPropertyName="BOExchange_NGConnectionString1" Provider="System.Data.SqlClient" />
  <Function Name="dbo.BO_DeleteSymbolSessionNew" Method="BO_DeleteSymbolSessionNew">
    <Parameter Name="Instruementid" Parameter="instruementid" Type="System.Int32" DbType="Int" />
    <Parameter Name="Day" Parameter="day" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
</Database>