<?xml version="1.0" encoding="utf-8"?>
<Database Name="BOExchange" Class="dbMan_BO_GetSymbolQuoteSessionDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=BOExchange;User ID=sa" SettingsObjectName="LtechIndia.BackOffice.BOEngine.DAL.Properties.Settings" SettingsPropertyName="BOExchangeConnectionString4" Provider="System.Data.SqlClient" />
  <Function Name="dbo.BO_GetSymbolQuotesession" Method="BO_GetSymbolQuotesession">
    <Parameter Name="Id" Parameter="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="Day" Parameter="day" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="BO_GetSymbolQuotesessionResult">
      <Column Name="Fk_InstruementID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Day" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Quotes" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EndQuotes" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>