#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LtechIndia.BackOffice.BOEngine.DAL.DB_New
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BOExchange")]
	public partial class dbMan_BO_GetSecurityTypeListDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public dbMan_BO_GetSecurityTypeListDataContext() : 
				base(global::LtechIndia.BackOffice.BOEngine.DAL.Properties.Settings.Default.BOExchangeConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public dbMan_BO_GetSecurityTypeListDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbMan_BO_GetSecurityTypeListDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbMan_BO_GetSecurityTypeListDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbMan_BO_GetSecurityTypeListDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.BO_GetSecurityTypeList")]
		public ISingleResult<BO_GetSecurityTypeListResult> BO_GetSecurityTypeList()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<BO_GetSecurityTypeListResult>)(result.ReturnValue));
		}
	}
	
	public partial class BO_GetSecurityTypeListResult
	{
		
		private int _PK_SecurityTypeID;
		
		private string _SecurityName;
		
		private string _SecurityDescription;
		
		public BO_GetSecurityTypeListResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PK_SecurityTypeID", DbType="Int NOT NULL")]
		public int PK_SecurityTypeID
		{
			get
			{
				return this._PK_SecurityTypeID;
			}
			set
			{
				if ((this._PK_SecurityTypeID != value))
				{
					this._PK_SecurityTypeID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SecurityName", DbType="VarChar(10)")]
		public string SecurityName
		{
			get
			{
				return this._SecurityName;
			}
			set
			{
				if ((this._SecurityName != value))
				{
					this._SecurityName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SecurityDescription", DbType="VarChar(50)")]
		public string SecurityDescription
		{
			get
			{
				return this._SecurityDescription;
			}
			set
			{
				if ((this._SecurityDescription != value))
				{
					this._SecurityDescription = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
