<?xml version="1.0" encoding="utf-8"?>
<Database Name="BOExchange" Class="dbMan_BO_GetBrokersCollateralInfoDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=192.168.1.87;Initial Catalog=BOExchange;Persist Security Info=True;User ID=sa" SettingsObjectName="LtechIndia.BackOffice.BOEngine.DAL.Properties.Settings" SettingsPropertyName="BOExchangeConnectionString1" Provider="System.Data.SqlClient" />
  <Function Name="dbo.BO_GetBrokersCollateralInfo" Method="BO_GetBrokersCollateralInfo">
    <ElementType Name="BO_GetBrokersCollateralInfoResult">
      <Column Name="PK_AccountGroupID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AccountGroupName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Owner" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Leverage" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ParentAccountGroupID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ParentOwner" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TotalCollateral" Type="System.Decimal" DbType="Decimal(0,0)" CanBeNull="true" />
      <Column Name="Unallocated" Type="System.Decimal" DbType="Decimal(0,0)" CanBeNull="true" />
      <Column Name="Utilized" Type="System.Decimal" DbType="Decimal(0,0)" CanBeNull="true" />
      <Column Name="PayInShortage" Type="System.Decimal" DbType="Decimal(0,0)" CanBeNull="true" />
      <Column Name="PayOutShortage" Type="System.Decimal" DbType="Decimal(0,0)" CanBeNull="true" />
      <Column Name="CollateralforTrading" Type="System.Decimal" DbType="Decimal(0,0)" CanBeNull="true" />
      <Column Name="IsEnable" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="BrokerType" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="FK_BrokerTypeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>