<?xml version="1.0" encoding="utf-8"?>
<Database Name="BOExchange" Class="dbMan_BO_GetIPAccessListDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=192.168.1.87;Initial Catalog=BOExchange;Persist Security Info=True;User ID=sa" SettingsObjectName="LtechIndia.BackOffice.BOEngine.DAL.Properties.Settings" SettingsPropertyName="BOExchangeConnectionString1" Provider="System.Data.SqlClient" />
  <Function Name="dbo.BO_GetIpAccessList" Method="BO_GetIpAccessList">
    <ElementType Name="BO_GetIpAccessListResult">
      <Column Name="PK_IPAccessListID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="From_IP" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="To_IP" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="Comment" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>