#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LtechIndia.BackOffice.BOEngine.DAL.DB_New
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BOExchange")]
	public partial class dbMan_BO_UpdateBankDetailsDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public dbMan_BO_UpdateBankDetailsDataContext() : 
				base(global::LtechIndia.BackOffice.BOEngine.DAL.Properties.Settings.Default.BOExchangeConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public dbMan_BO_UpdateBankDetailsDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbMan_BO_UpdateBankDetailsDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbMan_BO_UpdateBankDetailsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbMan_BO_UpdateBankDetailsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.BO_UpdateBankDetails")]
		public int BO_UpdateBankDetails([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PK_BankID", DbType="Int")] System.Nullable<int> pK_BankID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AccountHolderName", DbType="VarChar(50)")] string accountHolderName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BankAccountID", DbType="VarChar(50)")] string bankAccountID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BankName", DbType="VarChar(50)")] string bankName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FK_BankCountryID", DbType="Int")] System.Nullable<int> fK_BankCountryID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BankCity", DbType="VarChar(50)")] string bankCity, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BankZipCode", DbType="VarChar(50)")] string bankZipCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BankAddress1", DbType="VarChar(50)")] string bankAddress1, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BankAddress2", DbType="VarChar(50)")] string bankAddress2, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BankPhone", DbType="VarChar(50)")] string bankPhone, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BankFax", DbType="VarChar(50)")] string bankFax, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BankSwiftCode", DbType="VarChar(50)")] string bankSwiftCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FK_ParticipantID", DbType="Int")] System.Nullable<int> fK_ParticipantID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BankAccountType", DbType="VarChar(50)")] string bankAccountType, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BankIFSCCode", DbType="VarChar(20)")] string bankIFSCCode)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pK_BankID, accountHolderName, bankAccountID, bankName, fK_BankCountryID, bankCity, bankZipCode, bankAddress1, bankAddress2, bankPhone, bankFax, bankSwiftCode, fK_ParticipantID, bankAccountType, bankIFSCCode);
			return ((int)(result.ReturnValue));
		}
	}
}
#pragma warning restore 1591
