#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LtechIndia.BackOffice.BOEngine.DAL.DB_New
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="OMSExchange")]
	public partial class dbMan_BO_ModifyTradeDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public dbMan_BO_ModifyTradeDataContext() : 
				base(global::LtechIndia.BackOffice.BOEngine.DAL.Properties.Settings.Default.OMSExchangeConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dbMan_BO_ModifyTradeDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbMan_BO_ModifyTradeDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbMan_BO_ModifyTradeDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbMan_BO_ModifyTradeDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.BO_ModifyTrade")]
		public ISingleResult<BO_ModifyTradeResult> BO_ModifyTrade([global::System.Data.Linq.Mapping.ParameterAttribute(Name="OrderID", DbType="BigInt")] System.Nullable<long> orderID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AccountID", DbType="BigInt")] System.Nullable<long> accountID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LastPrice", DbType="Decimal")] System.Nullable<decimal> lastPrice)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), orderID, accountID, lastPrice);
			return ((ISingleResult<BO_ModifyTradeResult>)(result.ReturnValue));
		}
	}
	
	public partial class BO_ModifyTradeResult
	{
		
		private System.Nullable<int> _Column1;
		
		private string _Column2;
		
		public BO_ModifyTradeResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Column1", DbType="Int")]
		public System.Nullable<int> Column1
		{
			get
			{
				return this._Column1;
			}
			set
			{
				if ((this._Column1 != value))
				{
					this._Column1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Column2", DbType="NVarChar(4000)")]
		public string Column2
		{
			get
			{
				return this._Column2;
			}
			set
			{
				if ((this._Column2 != value))
				{
					this._Column2 = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
