<?xml version="1.0" encoding="utf-8"?>
<Database Name="BOExchange" Class="dbMan_BO_UpdateBrokersInfoDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=192.168.1.87;Initial Catalog=BOExchange;Persist Security Info=True;User ID=sa" SettingsObjectName="LtechIndia.BackOffice.BOEngine.DAL.Properties.Settings" SettingsPropertyName="BOExchangeConnectionString1" Provider="System.Data.SqlClient" />
  <Function Name="dbo.BO_UpdateBrokersInfo" Method="BO_UpdateBrokersInfo">
    <Parameter Name="BrokerID" Parameter="brokerID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Owner" Parameter="owner" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Leverage" Parameter="leverage" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="State" Parameter="state" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="IsEnable" Parameter="isEnable" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="BrokerType" Parameter="brokerType" Type="System.String" DbType="Char(10)" />
    <Parameter Name="Address" Parameter="address" Type="System.String" DbType="VarChar(256)" />
    <Parameter Name="City" Parameter="city" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Phone1" Parameter="phone1" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Phone2" Parameter="phone2" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Fax" Parameter="fax" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="EMail" Parameter="eMail" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="MarginCallLevel1" Parameter="marginCallLevel1" Type="System.Int32" DbType="Int" />
    <Parameter Name="MarginCallLevel2" Parameter="marginCallLevel2" Type="System.Int32" DbType="Int" />
    <Parameter Name="MarginCallLevel3" Parameter="marginCallLevel3" Type="System.Int32" DbType="Int" />
    <Parameter Name="News" Parameter="news" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="MaximumOrders" Parameter="maximumOrders" Type="System.String" DbType="VarChar(256)" />
    <Parameter Name="Maximumsymbols" Parameter="maximumsymbols" Type="System.String" DbType="VarChar(256)" />
    <Parameter Name="ParentBrokerID" Parameter="parentBrokerID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Roles" Parameter="roles" Type="System.String" DbType="VarChar(64)" />
    <Parameter Name="RoleId" Parameter="roleId" Type="System.Int32" DbType="Int" />
    <Parameter Name="RoleName" Parameter="roleName" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
</Database>