#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LtechIndia.BackOffice.BOEngine.DAL.DB_New
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BOExchange_NG")]
	public partial class dbMan_BO_SelectSymbolChargesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public dbMan_BO_SelectSymbolChargesDataContext() : 
				base(global::LtechIndia.BackOffice.BOEngine.DAL.Properties.Settings.Default.BOExchange_NGConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dbMan_BO_SelectSymbolChargesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbMan_BO_SelectSymbolChargesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbMan_BO_SelectSymbolChargesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbMan_BO_SelectSymbolChargesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.BO_SelectBrokersChargesInfo")]
		public ISingleResult<BO_SelectBrokersChargesInfoResult> BO_SelectBrokersChargesInfo([global::System.Data.Linq.Mapping.ParameterAttribute(Name="BrokersGroupID", DbType="Int")] System.Nullable<int> brokersGroupID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), brokersGroupID);
			return ((ISingleResult<BO_SelectBrokersChargesInfoResult>)(result.ReturnValue));
		}
	}
	
	public partial class BO_SelectBrokersChargesInfoResult
	{
		
		private int _PK_SymbolsChargesID;
		
		private int _FK_AccountGroupId;
		
		private int _FK_InstruementID;
		
		private string _Symbol;
		
		private string _FeeName;
		
		private System.Nullable<decimal> _FeeValue;
		
		private string _TaxName;
		
		private System.Nullable<decimal> _TaxPercent;
		
		public BO_SelectBrokersChargesInfoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PK_SymbolsChargesID", DbType="Int NOT NULL")]
		public int PK_SymbolsChargesID
		{
			get
			{
				return this._PK_SymbolsChargesID;
			}
			set
			{
				if ((this._PK_SymbolsChargesID != value))
				{
					this._PK_SymbolsChargesID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_AccountGroupId", DbType="Int NOT NULL")]
		public int FK_AccountGroupId
		{
			get
			{
				return this._FK_AccountGroupId;
			}
			set
			{
				if ((this._FK_AccountGroupId != value))
				{
					this._FK_AccountGroupId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_InstruementID", DbType="Int NOT NULL")]
		public int FK_InstruementID
		{
			get
			{
				return this._FK_InstruementID;
			}
			set
			{
				if ((this._FK_InstruementID != value))
				{
					this._FK_InstruementID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Symbol", DbType="VarChar(20)")]
		public string Symbol
		{
			get
			{
				return this._Symbol;
			}
			set
			{
				if ((this._Symbol != value))
				{
					this._Symbol = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FeeName", DbType="VarChar(50)")]
		public string FeeName
		{
			get
			{
				return this._FeeName;
			}
			set
			{
				if ((this._FeeName != value))
				{
					this._FeeName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FeeValue", DbType="Decimal(18,5)")]
		public System.Nullable<decimal> FeeValue
		{
			get
			{
				return this._FeeValue;
			}
			set
			{
				if ((this._FeeValue != value))
				{
					this._FeeValue = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaxName", DbType="VarChar(50)")]
		public string TaxName
		{
			get
			{
				return this._TaxName;
			}
			set
			{
				if ((this._TaxName != value))
				{
					this._TaxName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaxPercent", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> TaxPercent
		{
			get
			{
				return this._TaxPercent;
			}
			set
			{
				if ((this._TaxPercent != value))
				{
					this._TaxPercent = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
