#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LtechIndia.BackOffice.BOEngine.DAL.DB_New
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BOExchange_NG")]
	public partial class dbMan_BO_AddSymbolTradeSessionDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public dbMan_BO_AddSymbolTradeSessionDataContext() : 
				base(global::LtechIndia.BackOffice.BOEngine.DAL.Properties.Settings.Default.BOExchange_NGConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dbMan_BO_AddSymbolTradeSessionDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbMan_BO_AddSymbolTradeSessionDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbMan_BO_AddSymbolTradeSessionDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbMan_BO_AddSymbolTradeSessionDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.BO_AddSymbolTradeSession")]
		public int BO_AddSymbolTradeSession([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Instruementid", DbType="Int")] System.Nullable<int> instruementid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> day, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TradeStart", DbType="VarChar(50)")] string tradeStart, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TradeEnd", DbType="VarChar(50)")] string tradeEnd, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EODSession", DbType="Bit")] System.Nullable<bool> eODSession, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MarketMaker", DbType="Bit")] System.Nullable<bool> marketMaker)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), instruementid, day, tradeStart, tradeEnd, eODSession, marketMaker);
			return ((int)(result.ReturnValue));
		}
	}
}
#pragma warning restore 1591
