<?xml version="1.0" encoding="utf-8"?><Database Name="BOExchange_NG" Class="dbMan_BO_GetHedgeTypesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=127.0.0.1;Initial Catalog=BOExchange_NG;User ID=sa" SettingsObjectName="LtechIndia.BackOffice.BOEngine.DAL.Properties.Settings" SettingsPropertyName="BOExchange_NGConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.BO_GetHedgeTypes" Method="BO_GetHedgeTypes">
    <ElementType Name="BO_GetHedgeTypesResult">
      <Column Name="Hedge_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Hedge_Type" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>