<?xml version="1.0" encoding="utf-8"?><Database Name="BOExchange_NG" Class="dbMan_BO_UpdateAccountDetailsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=127.0.0.1;Initial Catalog=BOExchange_NG;User ID=sa" SettingsObjectName="LtechIndia.BackOffice.BOEngine.DAL.Properties.Settings" SettingsPropertyName="BOExchange_NGConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.BO_UpdateAccountDetails" Method="BO_UpdateAccountDetails">
    <Parameter Name="PK_AccountId" Parameter="pK_AccountId" Type="System.Int32" DbType="Int" />
    <Parameter Name="FK_ParticipantID" Parameter="fK_ParticipantID" Type="System.Int32" DbType="Int" />
    <Parameter Name="FK_AccountGroupID" Parameter="fK_AccountGroupID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Balance" Parameter="balance" Type="System.Decimal" DbType="Decimal(18,5)" />
    <Parameter Name="Equity" Parameter="equity" Type="System.Decimal" DbType="Decimal(18,5)" />
    <Parameter Name="Deleted" Parameter="deleted" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="UsedMargin" Parameter="usedMargin" Type="System.Decimal" DbType="Decimal(18,5)" />
    <Parameter Name="FK_Leverage" Parameter="fK_Leverage" Type="System.Int32" DbType="Int" />
    <Parameter Name="IsHedgingAllowed" Parameter="isHedgingAllowed" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="IsTradeEnable" Parameter="isTradeEnable" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="FK_Currency" Parameter="fK_Currency" Type="System.Int32" DbType="Int" />
    <Parameter Name="BuySideTurnOver" Parameter="buySideTurnOver" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="SellSideTurnOver" Parameter="sellSideTurnOver" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="BankID" Parameter="bankID" Type="System.Int32" DbType="Int" />
    <Parameter Name="HedgeTypeId" Parameter="hedgeTypeId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
</Database>