<?xml version="1.0" encoding="utf-8"?>
<Database Name="BOExchange" Class="dbMan_BO_InsertBrokersLogDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=BOExchange;Integrated Security=True" SettingsObjectName="LtechIndia.BackOffice.BOEngine.DAL.Properties.Settings" SettingsPropertyName="BOExchangeConnectionString7" Provider="System.Data.SqlClient" />
  <Function Name="dbo.BO_InsertBrokerLog" Method="BO_InsertBrokerLog">
    <Parameter Name="BrokerName" Parameter="brokerName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="BrokerID" Parameter="brokerID" Type="System.Int32" DbType="Int" />
    <Parameter Name="OperationName" Parameter="operationName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Message" Parameter="message" Type="System.String" DbType="VarChar(256)" />
    <Parameter Name="IPAddress" Parameter="iPAddress" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
</Database>