<?xml version="1.0" encoding="utf-8"?>
<Database Name="BOExchange" Class="dbMan_BO_GetPredefinedRolesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=192.168.1.87;Initial Catalog=BOExchange;User ID=sa" SettingsObjectName="LtechIndia.BackOffice.BOEngine.DAL.Properties.Settings" SettingsPropertyName="BOExchangeConnectionString3" Provider="System.Data.SqlClient" />
  <Function Name="dbo.BO_GetPredefinedRoles" Method="BO_GetPredefinedRoles">
    <ElementType Name="BO_GetPredefinedRolesResult">
      <Column Name="RoleId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SetOfAuth" Type="System.String" DbType="VarChar(64) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>