<?xml version="1.0" encoding="utf-8"?><Database Name="BOExchange_NG" Class="dbMan_BO_GetClientAccountInformationDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=127.0.0.1;Initial Catalog=BOExchange_NG;User ID=sa" SettingsObjectName="LtechIndia.BackOffice.BOEngine.DAL.Properties.Settings" SettingsPropertyName="BOExchange_NGConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.BO_GetClientAccountInformation" Method="BO_GetClientAccountInformation">
    <Parameter Name="ClientID" Parameter="clientID" Type="System.Int32" DbType="Int" />
    <ElementType Name="BO_GetClientAccountInformationResult">
      <Column Name="PK_AccountId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FK_ParticipantID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FK_AccountGroupID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Balance" Type="System.Decimal" DbType="Decimal(18,5) NOT NULL" CanBeNull="false" />
      <Column Name="Equity" Type="System.Decimal" DbType="Decimal(18,5) NOT NULL" CanBeNull="false" />
      <Column Name="Deleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UsedMargin" Type="System.Decimal" DbType="Decimal(18,5) NOT NULL" CanBeNull="false" />
      <Column Name="FK_Leverage" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsHedgingAllowed" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsTradeEnable" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="FK_Currency" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BuySideTurnOver" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="SellSideTurnOver" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="FK_BankID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReserveMargin" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="DayBuySideTurnOver" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="DaySellSideTurnOver" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="DayRealizedProfit" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="LP_Name" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="LPConnectionAccountID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IsLive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="FK_HedgeType_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>