<?xml version="1.0" encoding="utf-8"?><Database Name="BOExchange_NG" Class="dbMan_BO_GetInstrumentSwapsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=127.0.0.1;Initial Catalog=BOExchange_NG;User ID=sa" SettingsObjectName="LtechIndia.BackOffice.BOEngine.DAL.Properties.Settings" SettingsPropertyName="BOExchange_NGConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.BO_GetInstrumentSwaps" Method="BO_GetInstrumentSwaps">
    <Parameter Name="InstrumentId" Parameter="instrumentId" Type="System.Int32" DbType="Int" />
    <ElementType Name="BO_GetInstrumentSwapsResult">
      <Column Name="IsEnable" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="LongPosition" Type="System.Decimal" DbType="Decimal(18,5)" CanBeNull="true" />
      <Column Name="ShortPosition" Type="System.Decimal" DbType="Decimal(18,5)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>