<?xml version="1.0" encoding="utf-8"?><Database Name="BOExchange" Class="CountryListDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=203.190.146.73;Initial Catalog=BOExchange;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="BOExchangeConnectionString1" Provider="System.Data.SqlClient" />
  <Function Name="dbo.BO_GetCountryMasterInfo" Method="BO_GetCountryMasterInfo">
    <ElementType Name="BO_GetCountryMasterInfoResult">
      <Column Name="PK_CountryID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CountryName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Nationality" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CountryCode" Type="System.String" DbType="Char(3)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>