<?xml version="1.0" encoding="utf-8"?>
<Database Name="BOExchange" Class="dbMan_BO_GetRoutingPerformActionDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=192.168.1.101;Initial Catalog=BOExchange;User ID=sa" SettingsObjectName="DataAcessLogic.Properties.Settings" SettingsPropertyName="BOExchangeConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.BO_GetRoutingPerformAction" Method="BO_GetRoutingPerformAction">
    <ElementType Name="BO_GetRoutingPerformActionResult">
      <Column Name="PK_PerformActionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PerformActionName" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>