<?xml version="1.0" encoding="utf-8"?>
<Database Name="BOExchange" Class="dbMan_Report_DayClosingReportDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=192.168.1.101;Initial Catalog=BOExchange;User ID=sa" SettingsObjectName="DataAcessLogic.Properties.Settings" SettingsPropertyName="BOExchangeConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.Report_DayClosingReport" Method="Report_DayClosingReport">
    <Parameter Name="Symbol" Parameter="symbol" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="datetime" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="BrokerID" Parameter="brokerID" Type="System.Int32" DbType="Int" />
    <Parameter Name="ParentBrokerID" Parameter="parentBrokerID" Type="System.Int32" DbType="Int" />
    <ElementType Name="Report_DayClosingReportResult">
      <Column Name="TradeDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Symbol" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="TradeBuyUnit" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TradeSellUnit" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TradeBuyCapital" Type="System.Decimal" DbType="Decimal(0,0)" CanBeNull="true" />
      <Column Name="TradeSellCapital" Type="System.Decimal" DbType="Decimal(0,0)" CanBeNull="true" />
      <Column Name="OpenBuyQty" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OpenSellQty" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BrokerID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>