#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcessLogic.DBML
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BOExchange")]
	public partial class dbMan_BO_GetRoutingPerformActionDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public dbMan_BO_GetRoutingPerformActionDataContext() : 
				base(global::DataAcessLogic.Properties.Settings.Default.BOExchangeConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dbMan_BO_GetRoutingPerformActionDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbMan_BO_GetRoutingPerformActionDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbMan_BO_GetRoutingPerformActionDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbMan_BO_GetRoutingPerformActionDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.BO_GetRoutingPerformAction")]
		public ISingleResult<BO_GetRoutingPerformActionResult> BO_GetRoutingPerformAction()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<BO_GetRoutingPerformActionResult>)(result.ReturnValue));
		}
	}
	
	public partial class BO_GetRoutingPerformActionResult
	{
		
		private int _PK_PerformActionID;
		
		private string _PerformActionName;
		
		public BO_GetRoutingPerformActionResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PK_PerformActionID", DbType="Int NOT NULL")]
		public int PK_PerformActionID
		{
			get
			{
				return this._PK_PerformActionID;
			}
			set
			{
				if ((this._PK_PerformActionID != value))
				{
					this._PK_PerformActionID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PerformActionName", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string PerformActionName
		{
			get
			{
				return this._PerformActionName;
			}
			set
			{
				if ((this._PerformActionName != value))
				{
					this._PerformActionName = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
