<?xml version="1.0" encoding="utf-8"?>
<Database Name="BOExchange_NG" Class="dbMan_Report_ClientHoldingStocklDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=BOExchange_NG;Integrated Security=True" SettingsObjectName="DataAcessLogic.Properties.Settings" SettingsPropertyName="BOExchange_NGConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.Report_ClientHoldingStock" Method="Report_ClientHoldingStock">
    <Parameter Name="Symbol" Parameter="symbol" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="datetime" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="BrokerID" Parameter="brokerID" Type="System.Int32" DbType="Int" />
    <Parameter Name="ParentBrokerID" Parameter="parentBrokerID" Type="System.Int32" DbType="Int" />
    <Parameter Name="AccountID" Parameter="accountID" Type="System.Int32" DbType="Int" />
    <ElementType Name="Report_ClientHoldingStockResult">
      <Column Name="FK_AccountID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SecurityTypeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProductType" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="FK_Symbol" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Symbol" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="BuyUnit" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SellUnit" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Capital" Type="System.Decimal" DbType="Decimal(0,0)" CanBeNull="true" />
      <Column Name="DateTime" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="BrokerID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BrokerCompany" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ClintName" Type="System.String" DbType="VarChar(152)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>